# Generated by Django 4.2.3 on 2023-09-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringtoken',
            name='tags',
            field=models.ManyToManyField(related_name='tokens', to='api.tag'),
        ),
    ]
