# Generated by Django 4.2.3 on 2023-09-16 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stringtoken_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='updated_at'),
            preserve_default=False,
        ),
    ]
