# Generated by Django 4.2.3 on 2023-09-19 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_translation_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('language', models.CharField(max_length=2)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
                ('old_value', models.TextField(blank=True, verbose_name='old_value')),
                ('new_value', models.TextField(blank=True, verbose_name='new_value')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.stringtoken')),
            ],
        ),
    ]
