# Generated by Django 4.2.3 on 2023-10-31 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_projectaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccesstoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
