# Generated by Django 4.2.3 on 2023-11-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_projectaccesstoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringtoken',
            name='token',
            field=models.CharField(max_length=200, verbose_name='Token'),
        ),
    ]
