# Generated by Django 5.0.3 on 2024-05-15 09:50

import django.db.models.deletion
from django.db import migrations, models


def update_history_project_field(apps, schema_editor):
    History = apps.get_model("api", "historyrecord")
    for history in History.objects.all():
        history.project = history.token.project
        history.save()


def update_history_token_name_field(apps, schema_editor):
    History = apps.get_model("api", "historyrecord")
    for history in History.objects.all():
        history.token_name = history.token.token
        history.save()


def restore_history_tokens(apps, schema_editor):
    History = apps.get_model("api", "historyrecord")
    for history in History.objects.all():
        history.token = history.token_name
        history.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_stringtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='project',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.project'),
        ),
        migrations.RunPython(update_history_project_field),
        migrations.AlterField(
            model_name='historyrecord',
            name='project',
            field=models.ForeignKey(
                null=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.project'),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), (
                'deleted', 'Deleted')], default='updated', max_length=10),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='token_name',
            field=models.CharField(max_length=200, blank=True),
        ),
        migrations.RunPython(update_history_token_name_field),
        migrations.AlterField(
            model_name='historyrecord',
            name='token',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='historyrecord',
            name='token_name',
        )
    ]
