# Generated by Django 6.0.1 on 2026-03-07 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_historyrecord_project_historyrecord_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stringtoken',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='translation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='new', max_length=10),
        ),
        migrations.CreateModel(
            name='TranslationBundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('version_name', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationBundleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='api.translationbundle')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='api.language')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='api.translation')),
            ],
        ),
    ]
