# Generated by Django 6.0.1 on 2026-03-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_stringtoken_status_translation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluralTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plural_form', models.CharField(choices=[('zero', 'Zero'), ('one', 'One'), ('two', 'Two'), ('few', 'Few'), ('many', 'Many'), ('other', 'Other')], max_length=5)),
                ('value', models.TextField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plural_forms', to='api.translation')),
            ],
            options={
                'unique_together': {('translation', 'plural_form')},
            },
        ),
    ]
