# Generated by Django 6.0.1 on 2026-04-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pluraltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TranslationIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('deepl', 'DeepL'), ('google', 'Google Translate')], max_length=32)),
                ('api_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='api.project')),
            ],
            options={
                'unique_together': {('provider', 'project')},
            },
        ),
    ]
