# Generated by Django 6.0.6 on 2026-07-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_ai_provider_translation_memory_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBundleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_bundle_settings', to='api.project')),
            ],
        ),
    ]
