"""
Django settings for repository project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import warnings
from pathlib import Path
from .app_env import env_value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_value('APP_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_value('DEBUG', default=False)

_allowed_hosts_raw = env_value('ALLOWED_HOSTS', default='')
if _allowed_hosts_raw:
    ALLOWED_HOSTS = [h.strip()
                     for h in _allowed_hosts_raw.split(',') if h.strip()]
else:
    warnings.warn(
        "ALLOWED_HOSTS env var is not set. Defaulting to ['localhost', '127.0.0.1']. "
        "Set ALLOWED_HOSTS in production.",
        stacklevel=2,
    )
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in env_value('CORS_ORIGINS', default='').split(',') if o.strip()
]

CORS_URLS_REGEX = r'^/api/(plugin/.*|mcp)$'

CORS_ALLOW_HEADERS = [
    'Access-Token',
    'Content-Type'
]

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'knox',
    'api',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'webui',
    'django_q',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'repository.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'repository.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

engine = env_value("DB_ENGINE")
if engine == 'sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.' + engine,
            'NAME': env_value('DB_NAME'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.' + engine,
            'NAME': env_value('DB_NAME'),  # BASE_DIR / 'db.sqlite3',
            'HOST': env_value('DB_HOST'),
            'PORT': env_value('DB_PORT'),
            'USER': env_value('DB_USER'),
            'PASSWORD': env_value('DB_PASSWORD'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_KNOX = {
    'AUTO_REFRESH': True,
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "webui/static",
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'api.permissions.ProjectTwoFAPermission',
    ],
    'EXCEPTION_HANDLER': 'api.exception_handler.custom_exception_handler',
}

Q_CLUSTER = {
    'name': 'strings_repository',
    'workers': 2,
    'timeout': 300,
    'retry': 0,
    'save_limit': 100,
    'orm': 'default',
    'sync': False,
}
