from api.tests.file_processors.strings_file import *
from api.tests.file_processors.common import *
from api.tests.file_processors.android_resources import *
from api.tests.file_processors.json_file import *
from api.tests.file_processors.json_dict_file import *
from api.tests.file_processors.common_json_file import *
from api.tests.file_processors.xcstrings_file import *
from api.tests.file_processors.dotnet_file import *
from api.tests.file_processors.properties_file import *
from api.tests.file_processors.po_file import *
from api.tests.file_processors.mo_file import *
from api.tests.file_processors.excel_file import *
from api.tests.file_processors.file_processor import *
