from api.tests.views.project import *
from api.tests.views.language import *
from api.tests.views.roles import *
from api.tests.views.translation import *
from api.tests.views.string_token import *
from api.tests.views.export import *
from api.tests.views.import_api import *
from api.tests.views.history import *
from api.tests.views.webhook import *
from api.tests.views.bundle import *
from api.tests.views.glossary import *
