name: test build
permissions:
  contents: read

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  backend-test:
    name: Django tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Create required static directory
        run: mkdir -p webui/static

      - name: Run tests
        env:
          APP_SECRET_KEY: ci-secret-key
          DB_ENGINE: sqlite3
          DB_NAME: ci
        run: coverage run manage.py test api --verbosity=2

      - name: Coverage report
        run: coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  frontend-test:
    name: Web UI tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "25"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          files: coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
